[versions]
kotlin-gradle-plugin = "2.1.21"
ktlint-gradle-plugin = "12.1.2"
ktor = "3.1.3"
mockk = "1.14.2"

[plugins]
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-gradle-plugin" }

[libraries]
# Gradle Plugins
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }
ktlint-gradle-plugin = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint-gradle-plugin" }

kotlin-logging = { group = "io.github.microutils", name = "kotlin-logging", version = "3.0.5" }

# Ktor Server Dependencies
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }

ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }

# Kotlinx Serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.8.1" }

# Google Cloud
google-cloud-storage = { module = "com.google.cloud:google-cloud-storage", version = "2.52.3" }

# DuckDB
duckdb = { module = "org.duckdb:duckdb_jdbc", version = "1.3.0.0" }

# Testing Libraries
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }

[bundles]
ktor-server = [
    "ktor-server-core",
    "ktor-server-cio",
    "ktor-server-content-negotiation",
    "ktor-serialization-kotlinx-json",
    "ktor-server-status-pages",
    "ktor-server-call-logging"
]